name: "Docker Build and Push"

description: "Build Docker image and push to DockerHub"

inputs:
  docker_username:
    required: true
  docker_token:
    required: true
  image_name:
    required: true
  image_tag:
    required: true

runs:
  using: "composite"

  steps:
    - name: Login to DockerHub
      shell: bash
      run: |
        echo "${{ inputs.docker_token }}" | docker login -u "${{ inputs.docker_username }}" --password-stdin

    - name: Build Docker Image
      shell: bash
      run: |
        docker build -t ${{ inputs.image_name }}:${{ inputs.image_tag }} .

    - name: Push Docker Image
      shell: bash
      run: |
        docker push ${{ inputs.image_name }}:${{ inputs.image_tag }}
